name: OSV-Scanner
on:
  push:
    branches: [main, coreason-develop]
  pull_request:
    branches: [main, coreason-develop]
  schedule:
    - cron: '0 0 * * 1'

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  scan:
    name: OSV-Scanner
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.9.1"
