name: TruffleHog Secret Scan

on:
  push:
    branches: [ "main", "coreason-develop", "feat/add-security-scans" ]
  pull_request:
    branches: [ "main", "coreason-develop" ]

permissions: read-all

jobs:
  trufflehog:
    name: TruffleHog Secret Scanner
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@0fa069c12f0c7baf431041cd1e564a9c5058846c
        with:
          path: ./
          extra_args: --debug --only-verified
